# Generated by Django 4.2.17 on 2024-12-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainabilityabout',
            name='short_desc',
        ),
    ]
