# Generated by Django 4.2.17 on 2024-12-25 09:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0002_remove_sustainabilityabout_short_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpartner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourpartner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ourpartnerslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/partner-slider'),
        ),
        migrations.AlterField(
            model_name='ourpartnerslider',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ourpartnerslider',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sustainabilityabout',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sustainabilityabout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/sustain-about'),
        ),
        migrations.AlterField(
            model_name='sustainabilityabout',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sustainabilitybanner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sustainabilitybanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/sustain-banner'),
        ),
        migrations.AlterField(
            model_name='sustainabilitybanner',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
