# Generated by Django 4.2.17 on 2024-12-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sustainability', '0003_alter_ourpartner_description_alter_ourpartner_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourpartner',
            old_name='description',
            new_name='partner_desc',
        ),
        migrations.RenameField(
            model_name='sustainabilitybanner',
            old_name='description',
            new_name='banner_description',
        ),
        migrations.RenameField(
            model_name='sustainabilitybanner',
            old_name='image',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='sustainabilitybanner',
            old_name='title',
            new_name='banner_title',
        ),
        migrations.RemoveField(
            model_name='ourpartner',
            name='title',
        ),
    ]
