# Generated by Django 4.2.17 on 2025-01-29 09:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handi_craft', '0002_alter_handicraftbanner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handicraftbanner',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handicraftbanner',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='handicraftdata',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handicraftdata',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='handicraftdata',
            name='short_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handicraftdata',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
