# Generated by Django 4.2.17 on 2024-12-22 05:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_company_posts/')),
                ('date', models.DateField()),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='widget_posts/')),
                ('url', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
        migrations.DeleteModel(
            name='WidgetPost',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
    ]
