# Generated by Django 4.2.17 on 2025-01-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparelsproduct',
            name='type',
        ),
        migrations.DeleteModel(
            name='ApparelsType',
        ),
    ]
