# Generated by Django 4.2.17 on 2025-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0002_remove_apparelsproduct_type_delete_apparelstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparelsproduct',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
