# Generated by Django 4.2.17 on 2025-01-11 05:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('comments_count', models.IntegerField(default=0)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CompetitiveAdvantageImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='competitive/')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitiveAdvantageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='competitive-icon/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('short_title', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='feature-slider/')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flag_image', models.ImageField(upload_to='country_flags/')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCollaborationOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='office-image/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='about_images/')),
                ('title', models.CharField(max_length=150)),
                ('short_desc', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('start_at', models.IntegerField(blank=True, default=0, null=True)),
                ('mute', models.BooleanField(blank=True, default=False, null=True)),
                ('auto_play', models.BooleanField(blank=True, default=True, null=True)),
                ('loop', models.BooleanField(blank=True, default=True, null=True)),
                ('opacity', models.IntegerField(default=1)),
                ('show_controls', models.BooleanField(blank=True, default=False, null=True)),
                ('show_yt_logo', models.BooleanField(blank=True, default=False, null=True)),
                ('volume', models.IntegerField(blank=True, default=25, null=True)),
                ('short_title', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_video', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HowWeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='how-we-work/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetOurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='header-logo/')),
                ('about_company', models.ImageField(upload_to='header-logo/')),
                ('about_company_desc', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('maps_img', models.ImageField(upload_to='header-logo/')),
                ('maps_desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurFeatureImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='featureImg/')),
            ],
        ),
        migrations.CreateModel(
            name='OurFeatureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='feature-icon/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='products-info/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OurServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='service-data/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='why-choose-us/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_banner_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('home_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.homebanner')),
            ],
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='start_at',
            field=models.IntegerField(default=0, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='homebanner',
            name='opacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(max_length=60, null=True, blank=True),
        ),
    ]
