# Generated by Django 4.2.17 on 2025-01-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='start_at',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
