# Generated by Django 4.2.17 on 2024-12-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutservice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeSection',
            new_name='HomeBanner',
        ),
    ]
