# Generated by Django 4.2.17 on 2025-01-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homebanner_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='start_at',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
