# Generated by Django 4.2.17 on 2025-01-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homebanner_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='mute',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
