# Generated by Django 4.2.17 on 2024-12-21 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_homesection_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebanner',
            name='short_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homebanner',
            name='title',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
