# Generated by Django 4.2.17 on 2025-01-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homebanner_mute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='auto_play',
            field=models.BooleanField(default=False),
        ),
    ]
