# Generated by Django 4.2.17 on 2025-01-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homebanner_auto_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='auto_play',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='mute',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='start_at',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
