# Generated by Django 4.2.17 on 2025-01-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homebanner_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='loop',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='show_controls',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
