# Generated by Django 4.2.17 on 2024-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ourfeature_ourfeatureimg_ourfeatureinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('short_title', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='feature-slider/')),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
