# Generated by Django 4.2.17 on 2025-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homebanner_loop_alter_homebanner_show_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='opacity',
            field=models.IntegerField(default=0),
        ),
    ]
