# Generated by Django 4.2.17 on 2025-01-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homebanner_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='short_title',
            field=models.CharField(blank=True, max_length=990, null=True),
        ),
    ]
