# Generated by Django 4.2.17 on 2024-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetOurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
