# Generated by Django 4.2.17 on 2025-01-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homebanner_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=60, null=True),
        ),
    ]
