# Generated by Django 4.2.17 on 2025-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homebanner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannerimage',
            name='caption',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
