# Generated by Django 4.2.17 on 2024-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_blogpost_author_remove_blogpost_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flag_image', models.ImageField(upload_to='country_flags/')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCollaborationOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='office-image/')),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalCollaborationCountry',
        ),
    ]
