# Generated by Django 4.2.17 on 2025-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homebannerimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebannerimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
