# Generated by Django 4.2.17 on 2024-12-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_globalcollaboration_globalcollaborationoffice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcollaborationoffice',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
