# Generated by Django 4.2.17 on 2024-12-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_globalcollaborationoffice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='link',
            field=models.URLField(),
        ),
    ]
