# Generated by Django 4.2.17 on 2024-12-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homebanner_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurService',
        ),
    ]
