# Generated by Django 4.2.17 on 2024-12-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_ourservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurProduct',
        ),
    ]
