# Generated by Django 4.2.17 on 2024-12-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_ourproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurProductInfo',
            new_name='OurProduct',
        ),
    ]
