# Generated by Django 4.2.17 on 2024-12-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_ourproductinfo_ourproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitiveAdvantage',
        ),
    ]
