# Generated by Django 4.2.17 on 2024-12-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_competitiveadvantage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurFeature',
        ),
    ]
