# Generated by Django 4.2.17 on 2025-01-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_homebanner_auto_play_alter_homebanner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='start_at',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HomeBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_banner_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('home_banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.homebanner')),
            ],
        ),
    ]
